services:
  web:
    image: goodboyaen/sohoweb-fe:prod
    container_name: sohoweb-app-fe
    ports:
      - "4321:4321"
    restart: unless-stopped
    volumes:
      - ./public/uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
